version: "3.8"
services:
  paranoia:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${PORT:-2009}:${PORT:-2009}"
    command: ./paranoia_sysinfo